import {
  BusinessField,
  BusinessLineField,
  BusinessModuleDefinition,
} from './business-workspace.models';

const id = (key = 'id', label = 'Referencia'): BusinessField => ({
  key,
  label,
  source: 'path',
  type: 'text',
  required: true,
  hint: 'Se completa con la operación reciente; también puedes copiarlo desde un resultado.',
});
const text = (
  key: string,
  label: string,
  source: BusinessField['source'] = 'body',
  required = false,
): BusinessField => ({ key, label, source, type: 'text', required });
const number = (key: string, label: string, required = false): BusinessField => ({
  key,
  label,
  source: 'body',
  type: 'number',
  required,
});
const query = (
  key: string,
  label: string,
  type: BusinessField['type'] = 'text',
): BusinessField => ({
  key,
  label,
  source: 'query',
  type,
});
const bool = (key: string, label: string, defaultValue = true): BusinessField => ({
  key,
  label,
  source: 'body',
  type: 'boolean',
  defaultValue,
});
const lines = (
  key: string,
  label: string,
  itemFields: readonly BusinessLineField[],
): BusinessField => ({
  key,
  label,
  source: 'body',
  type: 'lines',
  required: true,
  itemFields,
});
const select = (
  key: string,
  label: string,
  source: BusinessField['source'],
  optionsEndpoint: string,
  required = false,
  optionLabelKey = 'name',
  optionSecondaryKey?: string,
  optionValueKey = 'id',
): BusinessField => ({
  key,
  label,
  source,
  type: 'select',
  required,
  optionsEndpoint,
  optionValueKey,
  optionLabelKey,
  optionSecondaryKey,
});
const multiSelect = (
  key: string,
  label: string,
  optionsEndpoint: string,
  optionLabelKey = 'name',
  optionSecondaryKey?: string,
  optionValueKey = 'id',
): BusinessField => ({
  ...select(
    key,
    label,
    'body',
    optionsEndpoint,
    true,
    optionLabelKey,
    optionSecondaryKey,
    optionValueKey,
  ),
  type: 'multi-select',
});
const warehouse = (
  key: string,
  label: string,
  source: BusinessField['source'],
  required = false,
): BusinessField => select(key, label, source, '/api/v1/warehouses', required);
const product = (
  key: string,
  label: string,
  source: BusinessField['source'],
  required = false,
): BusinessField =>
  select(key, label, source, '/api/v1/products?Page=1&PageSize=100', required, 'name', 'sku');
const customer = (
  key: string,
  label: string,
  source: BusinessField['source'],
  required = false,
): BusinessField => select(key, label, source, '/api/v1/customers', required, 'name', 'taxId');
const supplier = (
  key: string,
  label: string,
  source: BusinessField['source'],
  required = false,
): BusinessField => select(key, label, source, '/api/v1/suppliers', required, 'name', 'taxId');
const purchase = (
  key = 'id',
  label = 'Compra',
  source: BusinessField['source'] = 'path',
  required = true,
): BusinessField => select(key, label, source, '/api/v1/purchases', required, 'status', 'folio');
const accountReceivable = (
  key = 'id',
  label = 'Cuenta por cobrar',
  source: BusinessField['source'] = 'path',
  required = true,
): BusinessField =>
  select(key, label, source, '/api/v1/accounts-receivable', required, 'status', 'dueDate');
const reason: BusinessField = {
  key: 'reason',
  label: 'Motivo',
  source: 'body',
  type: 'textarea',
  required: true,
};
const period: readonly BusinessField[] = [
  query('From', 'Desde', 'date'),
  query('To', 'Hasta', 'date'),
];
const purchaseItems: readonly BusinessLineField[] = [
  {
    key: 'productId',
    label: 'Producto',
    type: 'select',
    required: true,
    optionsEndpoint: '/api/v1/products?Page=1&PageSize=100',
    optionLabelKey: 'name',
    optionSecondaryKey: 'sku',
  },
  { key: 'quantity', label: 'Cantidad', type: 'number', required: true, defaultValue: 1 },
  { key: 'unitCost', label: 'Costo unitario', type: 'number', required: true, defaultValue: 0 },
  { key: 'discount', label: 'Descuento', type: 'number', defaultValue: 0 },
];
const receiptItems = purchaseItems.filter((field) => field.key !== 'discount');

export const BUSINESS_MODULES: Readonly<Record<string, BusinessModuleDefinition>> = {
  F01: {
    key: 'F01',
    eyebrow: 'Seguridad',
    title: 'Usuarios, roles y permisos',
    description: 'Administra quién puede entrar y qué responsabilidades tiene dentro del sistema.',
    groups: { USR: 'Usuarios', ROL: 'Roles', PER: 'Permisos' },
    hiddenOperationIds: ['AUT-01', 'AUT-02', 'AUT-03'],
  },
  F03: {
    key: 'F03',
    eyebrow: 'Operación',
    title: 'Inventario',
    description: 'Consulta existencias y controla ajustes y transferencias entre almacenes.',
    groups: {
      'INV-0': 'Existencias',
      'INV-04': 'Ajustes',
      'INV-05': 'Ajustes',
      'INV-06': 'Ajustes',
      'INV-07': 'Transferencias',
    },
  },
  F04: {
    key: 'F04',
    eyebrow: 'Abastecimiento',
    title: 'Compras y recepciones',
    description: 'Da seguimiento a órdenes de compra y entradas de mercancía.',
    groups: { PUR: 'Compras', GRC: 'Recepciones' },
  },
  F06: {
    key: 'F06',
    eyebrow: 'Cobranza',
    title: 'Cuentas por cobrar',
    description: 'Consulta saldos, registra pagos y administra el crédito de tus clientes.',
    groups: { ACR: 'Cartera', CPY: 'Pagos y crédito' },
  },
  F07: {
    key: 'F07',
    eyebrow: 'Control',
    title: 'Auditoría y soporte',
    description: 'Investiga actividad, errores y cambios con trazabilidad de principio a fin.',
    groups: {
      AUD: 'Auditoría',
      CRS: 'Motivos de cancelación',
      OPN: 'Notas operativas',
      LOG: 'Monitoreo',
    },
  },
  F08: {
    key: 'F08',
    eyebrow: 'Análisis',
    title: 'Reportes',
    description: 'Consulta resultados de ventas, inventario, compras y cartera.',
    groups: { DSH: 'Resumen', RPT: 'Reportes' },
  },
  F09: {
    key: 'F09',
    eyebrow: 'Configuración',
    title: 'Administración',
    description: 'Configura folios, métodos de pago, políticas y herramientas de rastreo.',
    groups: {
      SET: 'Parámetros',
      FOL: 'Folios',
      PMT: 'Métodos de pago',
      PTR: 'Terminales de pago',
      PLC: 'Políticas',
      TRC: 'Rastreo',
    },
  },
};

export const BUSINESS_FIELDS: Readonly<Record<string, readonly BusinessField[]>> = {
  'USR-02': [
    text('name', 'Nombre completo', 'body', true),
    { ...text('username', 'Usuario', 'body', true) },
    { ...text('email', 'Correo', 'body', true), type: 'email' },
    { ...text('password', 'Contraseña', 'body', true), type: 'password' },
    multiSelect('roleIds', 'Roles', '/api/v1/roles'),
  ],
  'USR-03': [
    select('id', 'Usuario', 'path', '/api/v1/users', true, 'name', 'username'),
    text('name', 'Nombre completo', 'body', true),
    { ...text('email', 'Correo', 'body', true), type: 'email' },
    bool('active', 'Usuario activo'),
  ],
  'USR-04': [
    select('id', 'Usuario', 'path', '/api/v1/users', true, 'name', 'username'),
    multiSelect('ids', 'Roles', '/api/v1/roles'),
  ],
  'ROL-02': [text('name', 'Nombre del rol', 'body', true), text('description', 'Descripción')],
  'ROL-03': [
    select('id', 'Rol', 'path', '/api/v1/roles', true),
    multiSelect('permissionKeys', 'Permisos', '/api/v1/permissions', 'description', 'key', 'key'),
  ],

  'INV-01': [
    warehouse('WarehouseId', 'Almacén', 'query'),
    product('ProductId', 'Producto', 'query'),
  ],
  'INV-02': [
    product('ProductId', 'Producto', 'query'),
    warehouse('WarehouseId', 'Almacén', 'query'),
    ...period,
  ],
  'INV-04': [
    warehouse('warehouseId', 'Almacén', 'body', true),
    reason,
    lines('items', 'Productos contados', [
      {
        key: 'productId',
        label: 'Producto',
        type: 'select',
        required: true,
        optionsEndpoint: '/api/v1/products?Page=1&PageSize=100',
        optionLabelKey: 'name',
        optionSecondaryKey: 'sku',
      },
      {
        key: 'physicalQuantity',
        label: 'Existencia física',
        type: 'number',
        required: true,
        defaultValue: 0,
      },
      {
        key: 'unitCost',
        label: 'Costo unitario (MXN)',
        type: 'number',
        required: true,
        defaultValue: 0,
      },
    ]),
  ],
  'INV-05': [
    {
      ...select(
        'id',
        'Ajuste pendiente',
        'path',
        '/api/v1/inventory/adjustments',
        true,
        'status',
        'folio',
      ),
      optionFilterKey: 'status',
      optionFilterValue: 'Draft',
    },
  ],
  'INV-06': [
    select('id', 'Ajuste', 'path', '/api/v1/inventory/adjustments', true, 'status', 'folio'),
    reason,
  ],
  'INV-07': [
    product('productId', 'Producto', 'body', true),
    warehouse('sourceWarehouseId', 'Almacén origen', 'body', true),
    warehouse('destinationWarehouseId', 'Almacén destino', 'body', true),
    number('quantity', 'Cantidad', true),
    number('unitCost', 'Costo unitario', true),
    { ...text('notes', 'Notas'), type: 'textarea' },
  ],

  'PUR-02': [
    supplier('supplierId', 'Proveedor', 'body', true),
    number('tax', 'Impuestos'),
    { ...text('notes', 'Notas'), type: 'textarea' },
    lines('items', 'Productos solicitados', purchaseItems),
  ],
  'PUR-03': [purchase()],
  'PUR-04': [
    purchase(),
    supplier('supplierId', 'Proveedor', 'body', true),
    number('tax', 'Impuestos'),
    { ...text('notes', 'Notas'), type: 'textarea' },
    lines('items', 'Productos solicitados', purchaseItems),
  ],
  'PUR-05': [purchase()],
  'PUR-06': [purchase(), reason],
  'GRC-01': [select('id', 'Recepción', 'path', '/api/v1/goods-receipts', true, 'status', 'folio')],
  'GRC-02': [
    supplier('supplierId', 'Proveedor', 'body', true),
    purchase('purchaseOrderId', 'Orden de compra', 'body', false),
    warehouse('destinationWarehouseId', 'Almacén de destino', 'body', true),
    { ...text('notes', 'Notas'), type: 'textarea' },
    lines('items', 'Productos recibidos', receiptItems),
  ],
  'GRC-03': [
    {
      ...select(
        'id',
        'Recepción pendiente',
        'path',
        '/api/v1/goods-receipts',
        true,
        'status',
        'folio',
      ),
      optionFilterKey: 'status',
      optionFilterValue: 'Draft',
    },
  ],
  'GRC-04': [
    select('id', 'Recepción', 'path', '/api/v1/goods-receipts', true, 'status', 'folio'),
    reason,
  ],

  'ACR-01': [customer('customerId', 'Cliente', 'query')],
  'ACR-02': [accountReceivable()],
  'ACR-03': [customer('customerId', 'Cliente', 'path', true)],
  'CPY-01': [
    customer('customerId', 'Cliente', 'body', true),
    text('method', 'Forma de pago', 'body', true),
    number('amount', 'Importe', true),
    text('reference', 'Referencia'),
  ],
  'CPY-02': [
    id(),
    lines('allocations', 'Aplicación a documentos', [
      {
        key: 'accountReceivableId',
        label: 'Cuenta por cobrar',
        type: 'select',
        required: true,
        optionsEndpoint: '/api/v1/accounts-receivable',
        optionLabelKey: 'status',
        optionSecondaryKey: 'dueDate',
      },
      { key: 'amount', label: 'Importe', type: 'number', required: true, defaultValue: 0 },
    ]),
  ],
  'CPY-03': [id(), reason],
  'CPY-04': [
    customer('customerId', 'Cliente', 'path', true),
    number('newLimit', 'Nuevo límite', true),
    reason,
  ],

  'AUD-01': [
    ...period,
    query('Module', 'Módulo'),
    select('UserId', 'Usuario', 'query', '/api/v1/users', false, 'name', 'username'),
    query('Action', 'Acción'),
    query('EntityName', 'Tipo de registro'),
    query('CorrelationId', 'ID de correlación'),
    query('ReferenceFolio', 'Folio'),
  ],
  'AUD-02': [
    select(
      'id',
      'Cambio auditado',
      'path',
      '/api/v1/logs/audit?Page=1&PageSize=100',
      true,
      'action',
      'referenceFolio',
    ),
  ],
  'AUD-03': [id('entityName', 'Tipo de registro'), id('entityId', 'ID del registro')],
  'CRS-02': [
    text('code', 'Código', 'body', true),
    text('description', 'Descripción', 'body', true),
    text('module', 'Módulo', 'body', true),
    bool('requiresAuthorization', 'Requiere autorización', false),
    bool('active', 'Motivo activo'),
  ],
  'CRS-03': [
    select('id', 'Motivo', 'path', '/api/v1/cancellation-reasons', true, 'description', 'code'),
    text('code', 'Código', 'body', true),
    text('description', 'Descripción', 'body', true),
    text('module', 'Módulo', 'body', true),
    bool('requiresAuthorization', 'Requiere autorización', false),
    bool('active', 'Motivo activo'),
  ],
  'OPN-01': [
    text('entityName', 'Tipo de registro', 'body', true),
    text('entityId', 'ID del registro', 'body', true),
    { ...text('note', 'Nota', 'body', true), type: 'textarea' },
  ],
  'LOG-01': [
    ...period.map((field) => ({ ...field, key: field.key === 'From' ? 'dateFrom' : 'dateTo' })),
    query('module', 'Módulo'),
    query('action', 'Acción'),
    query('correlationId', 'ID de correlación'),
  ],
  'LOG-02': [
    select(
      'id',
      'Actividad',
      'path',
      '/api/v1/logs/activity?Page=1&PageSize=100',
      true,
      'action',
      'occurredAt',
    ),
  ],
  'LOG-03': [
    ...period.map((field) => ({ ...field, key: field.key === 'From' ? 'dateFrom' : 'dateTo' })),
    query('severity', 'Severidad'),
    query('correlationId', 'ID de correlación'),
  ],
  'LOG-04': [
    select(
      'id',
      'Error',
      'path',
      '/api/v1/logs/errors?Page=1&PageSize=100',
      true,
      'errorCode',
      'occurredAt',
    ),
  ],
  'LOG-05': [
    select(
      'id',
      'Error',
      'path',
      '/api/v1/logs/errors?Page=1&PageSize=100',
      true,
      'errorCode',
      'occurredAt',
    ),
    { ...text('notes', 'Notas de resolución'), type: 'textarea' },
  ],
  'LOG-06': [
    select(
      'id',
      'Error',
      'path',
      '/api/v1/logs/errors?Page=1&PageSize=100',
      true,
      'errorCode',
      'occurredAt',
    ),
  ],
  'LOG-07': [
    ...period.map((field) => ({ ...field, key: field.key === 'From' ? 'dateFrom' : 'dateTo' })),
    query('eventName', 'Evento'),
    query('status', 'Estado'),
  ],
  'LOG-08': [
    select(
      'eventId',
      'Evento',
      'path',
      '/api/v1/logs/events?Page=1&PageSize=100',
      true,
      'eventName',
      'status',
      'eventId',
    ),
  ],

  'RPT-01': period,
  'RPT-02': period,
  'RPT-03': period,
  'RPT-06': period,
  'RPT-07': [query('asOf', 'Fecha de corte', 'date')],

  'SET-02': [
    select(
      'key',
      'Configuración',
      'path',
      '/api/v1/admin/settings',
      true,
      'description',
      'key',
      'key',
    ),
    text('value', 'Valor', 'body', true),
    text('dataType', 'Tipo de dato', 'body', true),
    text('module', 'Módulo'),
    text('description', 'Descripción'),
  ],
  'FOL-02': [
    text('documentType', 'Tipo de documento', 'body', true),
    text('prefix', 'Prefijo', 'body', true),
    number('currentNumber', 'Número actual', true),
    number('padding', 'Longitud', true),
    bool('active', 'Secuencia activa'),
  ],
  'FOL-03': [
    select(
      'id',
      'Secuencia',
      'path',
      '/api/v1/admin/folio-sequences',
      true,
      'documentType',
      'prefix',
    ),
    text('documentType', 'Tipo de documento', 'body', true),
    text('prefix', 'Prefijo', 'body', true),
    number('currentNumber', 'Número actual', true),
    number('padding', 'Longitud', true),
    bool('active', 'Secuencia activa'),
  ],
  'PMT-02': [
    text('code', 'Código', 'body', true),
    text('name', 'Nombre', 'body', true),
    bool('requiresReference', 'Requiere referencia', false),
    bool('active', 'Método activo'),
  ],
  'PMT-03': [
    select('id', 'Método de pago', 'path', '/api/v1/admin/payment-methods', true, 'name', 'code'),
    text('code', 'Código', 'body', true),
    text('name', 'Nombre', 'body', true),
    bool('requiresReference', 'Requiere referencia', false),
    bool('active', 'Método activo'),
  ],
  'PTR-03': [
    select(
      'id',
      'Terminal',
      'path',
      '/api/v1/admin/payment-terminals',
      true,
      'name',
      'externalId',
    ),
  ],
  'PTR-04': [
    text('name', 'Nombre de la terminal', 'body', true),
    text('externalId', 'Identificador de Mercado Pago', 'body', true),
    { ...text('description', 'Descripción'), type: 'textarea' },
    bool('isDefault', 'Terminal predeterminada', false),
    bool('active', 'Terminal activa'),
  ],
  'PTR-05': [
    select(
      'id',
      'Terminal',
      'path',
      '/api/v1/admin/payment-terminals',
      true,
      'name',
      'externalId',
    ),
    text('name', 'Nombre de la terminal', 'body', true),
    text('externalId', 'Identificador de Mercado Pago', 'body', true),
    { ...text('description', 'Descripción'), type: 'textarea' },
    bool('isDefault', 'Terminal predeterminada', false),
    bool('active', 'Terminal activa'),
    number('rowVersion', 'Versión del registro'),
  ],
  'PTR-06': [
    select(
      'id',
      'Terminal activa',
      'path',
      '/api/v1/admin/payment-terminals',
      true,
      'name',
      'externalId',
    ),
  ],
  'PTR-07': [
    select(
      'id',
      'Terminal inactiva',
      'path',
      '/api/v1/admin/payment-terminals',
      true,
      'name',
      'externalId',
    ),
  ],
  'PLC-02': [
    bool('allowCreditSales', 'Permitir ventas a crédito'),
    number('defaultDueDays', 'Días de crédito', true),
    bool('requireAuthorizationOverLimit', 'Autorizar excedentes', false),
    bool('active', 'Política activa'),
  ],
  'PLC-04': [
    bool('allowNegativeStock', 'Permitir existencia negativa', false),
    bool('requireReasonForAdjustment', 'Exigir motivo en ajustes'),
    bool('active', 'Política activa'),
  ],
  'TRC-01': [id('operationId', 'ID de operación')],
  'TRC-02': [id('correlationId', 'ID de correlación')],
  'TRC-03': [id('folio', 'Folio del documento')],
  'TRC-04': [
    select(
      'eventId',
      'Evento',
      'path',
      '/api/v1/logs/events?Page=1&PageSize=100',
      true,
      'eventName',
      'status',
      'eventId',
    ),
  ],
};

export const BUSINESS_TITLES: Readonly<Record<string, string>> = {
  'USR-01': 'Directorio de usuarios',
  'USR-02': 'Crear usuario',
  'USR-03': 'Editar usuario',
  'USR-04': 'Asignar roles',
  'ROL-01': 'Catálogo de roles',
  'ROL-02': 'Crear rol',
  'ROL-03': 'Configurar permisos',
  'PER-01': 'Permisos disponibles',
  'INV-01': 'Consultar existencias',
  'INV-02': 'Revisar kardex',
  'INV-03': 'Productos con stock bajo',
  'INV-04': 'Registrar ajuste',
  'INV-05': 'Confirmar ajuste',
  'INV-06': 'Cancelar ajuste',
  'INV-07': 'Transferir inventario',
  'PUR-01': 'Órdenes de compra',
  'PUR-02': 'Nueva orden de compra',
  'PUR-03': 'Consultar una compra',
  'PUR-04': 'Editar compra abierta',
  'PUR-05': 'Confirmar compra',
  'PUR-06': 'Cancelar compra',
  'GRC-01': 'Consultar recepción',
  'GRC-02': 'Registrar recepción',
  'GRC-03': 'Cerrar recepción',
  'GRC-04': 'Cancelar recepción',
  'ACR-01': 'Consultar cartera',
  'ACR-02': 'Detalle de cuenta',
  'ACR-03': 'Estado de cuenta',
  'CPY-01': 'Registrar pago',
  'CPY-02': 'Aplicar pago',
  'CPY-03': 'Cancelar pago',
  'CPY-04': 'Cambiar límite de crédito',
  'AUD-01': 'Buscar cambios',
  'AUD-02': 'Detalle de cambio',
  'AUD-03': 'Historial de un registro',
  'CRS-01': 'Motivos disponibles',
  'CRS-02': 'Crear motivo',
  'CRS-03': 'Editar motivo',
  'OPN-01': 'Agregar nota operativa',
  'LOG-01': 'Actividad de usuarios',
  'LOG-02': 'Detalle de actividad',
  'LOG-03': 'Bandeja de errores',
  'LOG-04': 'Detalle del error',
  'LOG-05': 'Resolver error',
  'LOG-06': 'Reabrir error',
  'LOG-07': 'Eventos del sistema',
  'LOG-08': 'Detalle del evento',
  'DSH-01': 'Resumen operativo',
  'RPT-01': 'Resumen de ventas',
  'RPT-02': 'Ventas por producto',
  'RPT-03': 'Utilidad bruta',
  'RPT-04': 'Resumen de inventario',
  'RPT-05': 'Stock bajo',
  'RPT-06': 'Resumen de compras',
  'RPT-07': 'Antigüedad de saldos',
  'SET-01': 'Parámetros del sistema',
  'SET-02': 'Editar parámetro',
  'FOL-01': 'Secuencias de folios',
  'FOL-02': 'Crear secuencia',
  'FOL-03': 'Editar secuencia',
  'PMT-01': 'Métodos de pago',
  'PMT-02': 'Crear método de pago',
  'PMT-03': 'Editar método de pago',
  'PTR-01': 'Terminales de pago',
  'PTR-02': 'Terminales disponibles para cobro',
  'PTR-03': 'Consultar terminal',
  'PTR-04': 'Registrar terminal',
  'PTR-05': 'Editar terminal',
  'PTR-06': 'Dar de baja terminal',
  'PTR-07': 'Reactivar terminal',
  'PLC-01': 'Política de crédito',
  'PLC-02': 'Editar política de crédito',
  'PLC-03': 'Política de inventario',
  'PLC-04': 'Editar política de inventario',
  'TRC-01': 'Rastrear una operación',
  'TRC-02': 'Rastrear una correlación',
  'TRC-03': 'Rastrear un documento',
  'TRC-04': 'Rastrear un evento',
};
