<Project Sdk="Aspire.AppHost.Sdk/13.1.2">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>7c41b608-a441-4dcb-b3c5-5a6dcc23b399</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.4.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SpecificationPattern\SpecificationPattern.csproj" />
  </ItemGroup>

</Project>
